version: "3.8"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: app-image
    volumes:
      - ".:/var/www/html"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - app-network
    depends_on:
      - mysql

  nginx:
    container_name: webserver
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    container_name: db
    image: "mysql:8.0"
    environment:
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "prod-mysql:/var/lib/mysql"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  prod-mysql:
    driver: local
